export const InlineStyles = {
  BOLD: ["BOLD"],
  BOLD_ITALIC: ["BOLD", "ITALIC"],
  BOLD_ITALIC_UNDERLINE: ["BOLD", "ITALIC", "UNDERLINE"],
  BOLD_UNDERLINE: ["BOLD", "UNDERLINE"],
  CODE: ["CODE"],
  ITALIC: ["ITALIC"],
  ITALIC_UNDERLINE: ["ITALIC", "UNDERLINE"],
  NONE: [],
  STRIKETHROUGH: ["STRIKETHROUGH"],
  UNDERLINE: ["UNDERLINE"],
};
